package top.zjwwiki.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.zjwwiki.blogbackend.dto.ArticleSummaryResponse;
import top.zjwwiki.blogbackend.generated.Article;
import top.zjwwiki.blogbackend.generated.ArticleExample;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    long countByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int deleteByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int deleteByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int insert(Article row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int insertSelective(Article row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    List<Article> selectByExampleWithBLOBs(ArticleExample example);
    List<Article> selectArticleList();
    long countArticleSummaries(@Param("keyword") String keyword, @Param("category") String category);
    List<ArticleSummaryResponse> selectArticleSummaries(@Param("keyword") String keyword,
                                                        @Param("category") String category,
                                                        @Param("offset") int offset,
                                                        @Param("limit") int limit);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    Article selectByPrimaryKey(Long articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int updateByExampleSelective(@Param("row") Article row, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") Article row, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int updateByExample(@Param("row") Article row, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int updateByPrimaryKeySelective(Article row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(Article row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Feb 24 09:41:23 CST 2026
     */
    int updateByPrimaryKey(Article row);
}