spring.application.name=blog-backend
server.port=8081

# ====== ?????????? ======
spring.datasource.url=jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=blog
spring.datasource.password=Zjw123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====== MyBatis ?? ======
# ?? MBG ??? XML ???????? sqlMapGenerator ?????
mybatis.mapper-locations=classpath:mapper/*.xml

# ?????????? javaModelGenerator ?????
mybatis.type-aliases-package=top.zjwwiki.blogbackend.generated

# ??????????????? ? Java ???
mybatis.configuration.map-underscore-to-camel-case=true

# ????? SQL ??????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

jwt.secret=replace-with-a-long-random-secret-at-least-32-chars
jwt.expiration-ms=86400000